version: '3.6'

services:
  face-recognition-api:
    container_name: backend
    # image: node:14.15.4
    build: ./
    command: npm start
    working_dir: /usr/src/face-recognition-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/face-recognition-api